const express = require("express")
require("dotenv").config()
const cors = require("cors")
const app = express()
const cookieParser = require("cookie-parser")

const authRoutes = require("./routes/1. Authenticate")
const firstUnitRoutes = require("./routes/2. FirstUnits")
const secondUnitRoutes = require("./routes/3. SecondUnit")
const thirdUnitRoutes = require("./routes/4. ThirdUnits")
const fourthUnitRoutes = require("./routes/5. FourthUnit")
const positionRoutes = require("./routes/6. Positions")
const rankRoutes = require("./routes/7. Rank")
const moduleRoutes = require("./routes/8. Modules")
const permissionRoutes = require("./routes/9. Permissions")
const modulePermissionsRoute = require("./routes/10. ModulePermissions")
const userModulePermission = require("./routes/11. UserModulePermission")
const lessonCategoryRoute = require("./routes/12. LessonCategory")
const lessonRoute = require("./routes/13. Lesson")
const lessonVisiblityRoute = require("./routes/14. LessonVisiblity")
const lessonContentRoute = require("./routes/15. LessonContent")
const lessonContentImageRoute = require("./routes/16. LessonContentImage")
const lessonContentPdfRoute = require("./routes/17. LessonContentPdf")
const lessonContentVideo = require("./routes/18. LessonContentVideo")
const lessonRatingRoute = require("./routes/19. LessonRating")
const userLessonContentProgressRoute = require("./routes/20. UserLessonContentProgress")
const testCategoryRoute = require("./routes/21. TestCategory")
const testRoute = require("./routes/22. Test")
const testAnswersRoute = require("./routes/23. TestAnswers")
const userContentTestRoute = require("./routes/24. UserContentExamTest")
const newsCategory = require("./routes/25. News_category")
const newsRoute = require("./routes/26. News")
const usersRoute = require("./routes/27. Users")
const notificationRoute = require("./routes/28. Notification")
const rulesRoute = require("./routes/29. Rules")
const bookCategoryRoute = require("./routes/30. BookCategories")
const bookRoute = require("./routes/31. Book")
const bookFileRoute = require("./routes/32. BookFile")
const bookRatingRoute = require("./routes/33. BookRating")
const bookVisiblityRoute = require("./routes/34. BookVisiblity")
const lessonContentTestRoute = require("./routes/35. LessonContentTest")
const UserDashboardRoute = require("./routes/36. UserDashboard")
const angilalSurgaltRoute = require("./routes/37. AngilalSurgalt")

app.use(cors({
  origin: ["http://localhost:5173"],
  credentials: true
}));

app.use(cookieParser())
app.use(express.json())

app.use('/uploads', express.static('uploads'));

app.use("/api/v1", authRoutes)
app.use("/api/v1", firstUnitRoutes)
app.use("/api/v1", secondUnitRoutes)
app.use("/api/v1", thirdUnitRoutes)
app.use("/api/v1", fourthUnitRoutes)
app.use("/api/v1", positionRoutes)
app.use("/api/v1", rankRoutes)
app.use("/api/v1", moduleRoutes)
app.use("/api/v1", permissionRoutes)
app.use("/api/v1", modulePermissionsRoute)
app.use("/api/v1", userModulePermission)
app.use("/api/v1", lessonCategoryRoute)
app.use("/api/v1", lessonRoute)
app.use("/api/v1", lessonVisiblityRoute)
app.use("/api/v1", lessonContentRoute)
app.use("/api/v1", lessonContentImageRoute)
app.use("/api/v1", lessonContentPdfRoute)
app.use("/api/v1", lessonContentVideo)
app.use("/api/v1", lessonRatingRoute)
app.use("/api/v1", userLessonContentProgressRoute)
app.use("/api/v1", testCategoryRoute)
app.use("/api/v1", testRoute)
app.use("/api/v1", testAnswersRoute)
app.use("/api/v1", userContentTestRoute)
app.use("/api/v1", newsCategory)
app.use("/api/v1", newsRoute)
app.use("/api/v1", usersRoute)
app.use("/api/v1", notificationRoute)
app.use("/api/v1", rulesRoute)
app.use("/api/v1", bookCategoryRoute)
app.use("/api/v1", bookRoute )
app.use("/api/v1", bookFileRoute )
app.use("/api/v1", bookRatingRoute )
app.use("/api/v1", bookVisiblityRoute )
app.use("/api/v1", lessonContentTestRoute )
app.use("/api/v1", UserDashboardRoute )
app.use("/api/v1", angilalSurgaltRoute )


app.listen(process.env.PORT, () => {
    console.log("APP LISTENING: " + " " + process.env.PORT)
})
